### ISSUE TITLE
Le compteur de vues de TP ne compte pas pareil en fonction des pages

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#102]
Je viens de remarquer qu'à chaque fois que je fais une correction sur cette page, le compte s'incrémente de 1 (ça veut aussi dire qu'il me compte...): https://wiki.tripleperformance.fr/wiki/Irrigation_en_grandes_cultures

Mais pas pour ce type de page par exemple, où le compteur se met à jour que le lendemain matin : https://wiki.tripleperformance.fr/wiki/Monter_un_projet_collectif_de_m%C3%A9thanisation_agricole
Pour info cette page a été diffusée sur les réseaux, le jour de la diffusion il n'y a eu aucune vue en plus alors que Google Analytics en a comptabilisé plus de 235.

On n'a donc pas la même façon de compter et de mettre à jour le compteur en fonction des pages de TP

**Comment by bertrandgorge** [comment]
https://backlinko.com/ad-blockers-users#ad-blocking-by-country
