### ISSUE TITLE
Lors de l'inscription, les icônes des productions ne s'affichent pas 

### ISSUE THREAD

**Issue by paulinepirola** [neayi/tripleperformance#12]
![image](https://user-images.githubusercontent.com/82869223/115359510-0898f700-a1bf-11eb-9338-f95a6da4b184.png)

**Comment by bertrandgorge** [comment]
J'ai corrigé ça hier théoriquement. Peux-tu réessayer avec éventuellement en navigation privée pour tester ça ?

**Comment by paulinepirola** [comment]
Essai à l'instant en navigation privée : 
![image](https://user-images.githubusercontent.com/82869223/115360989-709c0d00-a1c0-11eb-93ae-46e48368762a.png)

**Comment by bertrandgorge** [comment]
zut

**Comment by bertrandgorge** [comment]
Ok - c'est parce que j'ai mis à jour le code, y a une manipe à faire à chaque fois, je ne savais pas.

![image](https://user-images.githubusercontent.com/12585613/115372870-a0044700-a1cb-11eb-9adb-f8ecb63f539e.png)
