### ISSUE TITLE
L'inscription a TP via Twitter ne semble pas fonctionner

### ISSUE THREAD

**Issue by paulinepirola** [neayi/tripleperformance#13]
Résultat quand on clique sur le logo twitter : 
https://insights.preprod.tripleperformance.fr/register/twitter

**Comment by bertrandgorge** [comment]
C'est corrigé. C'était la configuration de twitter qui n'était pas faite pour la préprod. (pour future référence voir : https://developer.twitter.com/en/portal/apps/16695369/settings)
