### ISSUE TITLE
Icones de cultures manquantes 

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#130]
Voici les liens vers les icônes à créer :
-Céréales : https://thenounproject.com/icon/cereals-4260183/
-Cultures fourragère : https://thenounproject.com/icon/haystack-2788927/ ou https://thenounproject.com/icon/hay-bales-bundle-2685469/
-Méteil : https://thenounproject.com/icon/multi-species-cover-crop-4476029/ ou https://thenounproject.com/icon/meadow-4487933/
-Petit pois : https://thenounproject.com/icon/peas-437003/
-Soja : https://thenounproject.com/icon/soya-beans-4452872/
-Féverole : https://thenounproject.com/icon/cereals-3817520/
-Luzerne : je ne trouve pas d'icone valable sur the Nounproject. Si tu as des idées où en chercher... Au pire mets ça au lieu des agrumes : https://thenounproject.com/icon/meadow-4325609/

**Comment by bertrandgorge** [comment]
C'est fait : 


Luzerne.png
Féverole.png
Soja.png
Petit pois.png
Méteil.png
Cultures fourragères.png
Céréales.png

**Comment by bertrandgorge** [comment]
https://wiki.tripleperformance.fr/wiki/Aide:Caracteristiques_sans_ic%C3%B4nes
