### ISSUE TITLE
Ajouter les icônes suivantes

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#137]
Aubergine : https://thenounproject.com/icon/aubergine-3763790/
Fraise : https://thenounproject.com/icon/strawberry-4509573/
Tomate : https://thenounproject.com/icon/tomato-4496120/
Coriandre : https://thenounproject.com/icon/coriander-2710034/
Romarin : https://thenounproject.com/icon/rosemary-2595723/
Laitue : https://thenounproject.com/icon/lettuce-842052/
Culture sous abri : https://thenounproject.com/icon/greenhouse-7856/

**Comment by bertrandgorge** [comment]
C'est fait - il faut compléter les pages suivantes du coup (ou les fusionner avec d'autres ?)

- https://wiki.tripleperformance.fr/wiki/Culture_sous_abri
- https://wiki.tripleperformance.fr/wiki/Laitue


A l'occasion il faudrait aussi compléter les pages :  
- https://wiki.tripleperformance.fr/wiki/Syst%C3%A8me_non_irrigu%C3%A9
- https://wiki.tripleperformance.fr/wiki/Non_labour
