### ISSUE TITLE
Liste de choix dans les formulaires 

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#144]
Quand on créé une page avec le formulaire "Pratique", dans les listes de choix après le bloc description la sélection du mot tapé ne se fait pas, il faut scroller jusqu'à sa position dans la liste et cliquer dessus pour qu'il s'affiche correctement dans le champ.

Je ne suis pas sûre d'être claire par écrit, mais par exemple tu tapes "noue" et tu fais enter et ça te met autre chose, il faut taper noue et scroller dans  la liste jusqu'à "Noue" qui est mis en gras et cliquer dessus pour que ça l'intègre correctement dans la champ.

**Comment by bertrandgorge** [comment]
Hello, c'est encore d'actualité ça du coup ?

**Comment by AstridRobette** [comment]
Ca a l'air de fonctionner !

*Astrid Robette*
*Responsable éditorial & Community manager*
Triple Performance <http://www.tripleperformance.fr> by *Neayi*
<http://www.neayi.com>

*Derniers jours pour participer à la campagne de financement participatif
sur BlueBees <https://bluebees.fr/fr/project/1022> !*



Le mar. 26 juil. 2022 à 09:54, Bertrand Gorge ***@***.***> a
écrit :
