### ISSUE TITLE
Défaut d'affichage de la Côte d'or dans la carte

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#151]
Sur ces pages : 
https://wiki.tripleperformance.fr/wiki/Passer_en_ACS_en_syst%C3%A8me_grandes_cultures_et_cultures_fourrag%C3%A8res
https://wiki.tripleperformance.fr/wiki/Passer_en_ACS_en_polyculture_%C3%A9levage#cite_ref-1
Le département de la Côte d'or ne s'affiche pas dans la carte alors qu'ils s'affiche dans le contexte.

**Comment by bertrandgorge** [comment]
Je ne reproduis pas - peux-tu réessayer ?

**Comment by AstridRobette** [comment]
Bon ben, il s'affiche maintenant...
--
*Astrid Robette*
*Responsable éditorial & Community manager*
Triple Performance <http://www.tripleperformance.fr> by *Neayi*
<http://www.neayi.com>




Le mar. 22 févr. 2022 à 09:05, Bertrand Gorge ***@***.***> a
écrit :
