### ISSUE TITLE
Nouvelles icônes à créer

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#152]
Poivron : https://thenounproject.com/icon/pepper-3435220/
Melon : https://thenounproject.com/icon/melon-1510413/
Radis : https://thenounproject.com/icon/radish-1178792/
Sorgho : https://thenounproject.com/icon/sorghum-48572/
Lentille : https://thenounproject.com/icon/lentils-1510335/
Pois chiche : https://thenounproject.com/icon/chickpea-4012683/

**Comment by bertrandgorge** [comment]
C'est fait : https://wiki.tripleperformance.fr/wiki/Mise_en_place_d%27un_atelier_c%C3%A9r%C3%A9alier_en_agriculture_de_conservation_des_sols
