### ISSUE TITLE
Mise à jour du formulaire de création d'une pratique

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#155]
Dans le formulaire de création d'une pratique, dans le champ "Cette technique s'applique aux cultures suivantes" : Maraîchage et Horticulture ne sont pas présents dans la liste de choix alors que Grandes cultures, Viticulture et Arboriculture y sont bien.

**Comment by AstridRobette** [comment]
Etrange car aujourd'hui je crée une nouvelle pratique et Maraîchage, Viticulture, Arboriculture y sont bien mais pas Grandes Cultures ni Horticulture...

**Comment by bertrandgorge** [comment]
Pour Maraîchage et Horticulture c'est normal, c'est une production (champ plus haut). C'est pareil pour arbo et viti...

**Comment by AstridRobette** [comment]
Pourquoi des fois on les retrouve dans la liste et pas d'autres fois alors ?
--
*Astrid Robette*
*Responsable éditorial & Community manager*
Triple Performance <http://www.tripleperformance.fr> by *Neayi*
<http://www.neayi.com>




Le mer. 9 mars 2022 à 11:49, Bertrand Gorge ***@***.***> a
écrit :
