### ISSUE TITLE
Double icone arbo dans la page de création de compte

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#197]
https://insights.tripleperformance.fr/profile-wizard
Dans la page de création de compte, à l'étape où l'on renseigne ses cultures il y a 2 fois arboriculture
![image](https://user-images.githubusercontent.com/75373764/167589166-fec56763-6fe7-452d-9880-3e93faecc31b.png)

**Comment by bertrandgorge** [comment]
Corrigé
