### ISSUE TITLE
Problème dans la génération des UTM

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#218]
Un # est mis à la place du ?
![image](https://user-images.githubusercontent.com/75373764/183373031-0293f64c-90cf-4a4c-8cf6-cc3c6e6b4a88.png)

Fichier de génération des urls utilisées pour les posts FB, onglet "Noms des groupes pour url", colonne H : https://docs.google.com/spreadsheets/d/1Y5YTV64Vt6RbgW4nWW4llfYtQ-ZpfnOkayJhO65nCI0/edit#gid=151346091

**Comment by bertrandgorge** [comment]
Alors, ça vient de ce que dans l'URL y avait un titre de chapitre qui avait été cliqué : 

```
http://wiki.tripleperformance.fr/wiki/Comprendre_et_%C3%A9viter_une_faim_d%27azote#Comment_corriger_la_faim_d%E2%80%99azote_?
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Ce chapitre contenait par ailleurs un point d'interrogation - bref, ça a mis le bazar ! J'ai corrigé directement dans la DB et j'ai corrigé l'excel pour éviter que ça ne se remanifeste !

**Comment by AstridRobette** [comment]
Merci!

*Astrid Robette*
*Responsable éditorial & Community manager*
Triple Performance <http://www.tripleperformance.fr> by *Neayi*
<http://www.neayi.com>



Le mar. 23 août 2022 à 17:12, Bertrand Gorge ***@***.***> a
écrit :
