### ISSUE TITLE
Menu déroulant pas complet en fin de page 

### ISSUE THREAD

**Issue by paulinepirola** [neayi/tripleperformance#23]
Si on souhaite modifier un article en cours de lecture, on clique sur le nouveau menu déroulant et le bouton "modifier" n'est pas visible : 
![image](https://user-images.githubusercontent.com/82869223/115577123-6e22db80-a2c4-11eb-912b-4e5d8d31a3f0.png)

Il faut remonter jusqu'en haut de l'article pour faire apparaître l'action "modifier" : 
![image](https://user-images.githubusercontent.com/82869223/115577325-9f031080-a2c4-11eb-9d1d-6413a6313e32.png)

**Comment by bertrandgorge** [comment]
Hum, je n'arrive pas à le gérer. Je verrai plus tard !
