### ISSUE TITLE
Créer les icones Basilic.png, Ciboulette.png et Aneth.png

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#231]
Basilic : https://thenounproject.com/icon/basil-1763253/
Ciboulette : https://thenounproject.com/icon/chives-4197784/
Aneth : https://thenounproject.com/icon/dill-5141062/

**Comment by bertrandgorge** [comment]
C'est fait !

**Comment by AstridRobette** [comment]
Merci!

*Astrid Robette*
*Responsable éditorial & Community manager*
Triple Performance <http://www.tripleperformance.fr> by *Neayi*
<http://www.neayi.com>



Le ven. 14 oct. 2022 à 11:21, Bertrand Gorge ***@***.***> a
écrit :
