### ISSUE TITLE
Ajouter les icônes lin, cassis, groseillier, framboise, betterave

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#239]
Lin : https://thenounproject.com/icon/flax-3845160/
Cassis : https://thenounproject.com/icon/blackcurrant-4133134/
Groseillier : https://thenounproject.com/icon/blackcurrant-563025/
Framboise : https://thenounproject.com/icon/raspberry-1535711/
Betterave : https://thenounproject.com/icon/beet-2619309/

**Comment by bertrandgorge** [comment]
Pour la betterave y avait déjà l'icône mais il fallait préciser si c'était de la sucrière, rouge (maraichère) ou fourragère : https://wiki.tripleperformance.fr/wiki/Betterave (j'ai mis la même icone aux 3)

**Comment by bertrandgorge** [comment]
C'est tout bon
