### ISSUE TITLE
Bug recherche Agrilismat

### ISSUE THREAD

**Issue by PaullouisTPerformance1** [neayi/tripleperformance#263]
Quand on est sur cette page "https://wiki.tripleperformance.fr/wiki/Programme_Agrilismat?offset=10" certains résultats de recherche font apparaitre des doublons de leurs catégories. 
Ces doublons disparaissent quand on clique sur l'article en question. 

Par exemple :
![1](https://user-images.githubusercontent.com/121863891/210849407-5061cb91-a0a1-4074-b9df-ecb841a9e550.png)

![1](https://user-images.githubusercontent.com/121863891/210849492-6d750c5b-f0dc-48b3-81dd-edc89940b6a3.png)

**Comment by bertrandgorge** [comment]
C'est corrigé
