### ISSUE TITLE
LinkTitle ne respecte pas l'UTF8 et coupe les mots au milieu des accents ?

### ISSUE THREAD

**Issue by bertrandgorge** [neayi/tripleperformance#417]
https://wiki.tripleperformance.fr/index.php?title=G%C3%A9rer_les_carences_en_grandes_cultures&type=revision&diff=143255&oldid=140468

**Comment by bertrandgorge** [comment]
Pour exécuter linktitles-cli.php sur la page Sandbox en preprod : 

`php wiki.php --fr --preprod linktitles-cli.php --page Sandbox`

==> la commande qui sera exécutée est : 
`
docker compose -f /var/www/tripleperformance/docker-compose.prod.yml -f /var/www/tripleperformance/docker-compose.preprod.yml -f /var/www/tripleperformance/docker-compose.workers.yml run --rm   --user=www-data:www-data  --env MW_INSTALL_PATH=/var/www/html --env WIKI_LANGUAGE=fr  web_preprod sh -c "php /var/www/html/extensions/LinkTitles/linktitles-cli.php --page Sandbox"
`

En dev il suffit de faire : 
`php wiki.php linktitles-cli.php --page Sandbox`

**Comment by bertrandgorge** [comment]
Pour tester le remplacement en live après chaque édition de la page : 

`
$wgLinkTitlesParseOnEdit = true;
`

**Comment by bertrandgorge** [comment]
Voir https://www.php.net/manual/fr/function.mb-split.php en remplacement mb_preg_split !

**Comment by alterphp** [comment]
Fixed by https://github.com/neayi/LinkTitles/pull/1
