### ISSUE TITLE
Liste déroulante des Objectifs dans formulaire ne s'affiche plus 

### ISSUE THREAD

**Issue by paulinepirola** [neayi/tripleperformance#54]
![image](https://user-images.githubusercontent.com/82869223/122049751-0e880e80-cde3-11eb-9873-262d3346d1a4.png)

Il me semble qu'une liste déroulante avec les objectifs s'affichait initialement ? Maintenant c'est écrit "No results found"

**Comment by bertrandgorge** [comment]
C'est corrigé.
