### ISSUE TITLE
Mise en page des annexes en utilisant le formulaire 

### ISSUE THREAD

**Issue by paulinepirola** [neayi/tripleperformance#55]
![image](https://user-images.githubusercontent.com/82869223/122180444-b86da680-ce88-11eb-8318-575f98b44484.png)

Lorsqu'on utilise le formulaire de création Pratique, les cultures concernées par la pratique sont centrées dans le paragraphe, est-ce normal ?

**Comment by bertrandgorge** [comment]
Oui - pour l'instant je ne peux pas faire mieux... C'est les navigateurs qui décident de faire ça comme ça !
