### ISSUE TITLE
Notification de question reçue

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#80]
La notification comme quoi une question a été posée sur une page sont envoyée aléatoirement...
Pauline a reçu la notif pour le REX https://wiki.tripleperformance.fr/index.php?curid=13691 et pas moi alors que je suis et que j'ai applaudi la page

**Comment by bertrandgorge** [comment]
Je ferme ce bug, mais il ne suffit pas d'applaudir pour recevoir les notifs de commentaires, il faut suivre la page !

**Comment by AstridRobette** [comment]
Oui je sais qu'il faut suivre la page pour recevoir les notifs, ce que je voulais dire c'est que Pauline et moi avions fait les mêmes choses sur cette page et qu'elle avait été notifiée et pas moi.
