### ISSUE TITLE
L'affichage des REX liés à une vidéo Vers de terre prod ne marche pas

### ISSUE THREAD

**Issue by AstridRobette** [neayi/tripleperformance#87]
Dans les pages  des vidéos de VDTP les REX associés au sujet de la page ne ressortent pas malgré la présence de :
==Annexes==
{{Retours d'expériences évoquant cette page}}

Ex de page : https://wiki.tripleperformance.fr/wiki/Fran%C3%A7ois_Mulet_-_%C3%89cologie_des_vers_de_terre_%26_reconstruction_de_la_fertilit%C3%A9_des_sols

**Comment by bertrandgorge** [comment]
Corrigé a priori
